// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { config } from "dotenv";
import { defineConfig } from "prisma/config";

// Next.js uses .env.local — load it explicitly so Prisma CLI can read it
config({ path: ".env.local" });

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Transaction pooler (port 6543) — reachable via IPv6 from this machine
    url: process.env["DATABASE_POOLER_URL"],
  },
});
